import type React from 'react';

/** Color palette for node types. */
export const TYPE_COLORS: Record<string, string> = {
  question: '#3b82f6',
  finding: '#f59e0b',
  source: '#22c55e',
  experiment: '#8b5cf6',
  checkpoint: '#f97316',
  tool_building: '#06b6d4',
  gap: '#ec4899',
};

/** Color palette for status values. */
export const STATUS_COLORS: Record<string, string> = {
  completed: '#22c55e',
  active: '#3b82f6',
  failed: '#ef4444',
  queued: '#9ca3af',
  discarded: '#6b7280',
  open: '#3b82f6',
  resolved: '#22c55e',
  building: '#f59e0b',
  ready: '#22c55e',
  kept: '#22c55e',
};

export const ds: Record<string, React.CSSProperties> = {
  section: {
    marginTop: 16,
    paddingTop: 12,
    borderTop: '1px solid #f3f4f6',
  },
  sectionTitle: {
    margin: '0 0 8px',
    fontSize: 11,
    fontWeight: 600,
    color: '#9ca3af',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
  },
  text: {
    fontSize: 13,
    color: '#374151',
    lineHeight: 1.5,
    margin: '6px 0',
  },
  largeText: {
    fontSize: 14,
    color: '#111827',
    lineHeight: 1.5,
    fontWeight: 500,
    margin: '8px 0',
  },
  codeBlock: {
    background: '#f8f9fa',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    fontSize: 11,
    padding: 10,
    borderRadius: 6,
    overflowX: 'auto' as const,
    whiteSpace: 'pre-wrap' as const,
    wordBreak: 'break-all' as const,
    color: '#1f2937',
    margin: '8px 0',
    maxHeight: 200,
    overflowY: 'auto' as const,
  },
  badge: {
    display: 'inline-block',
    fontSize: 10,
    fontWeight: 600,
    padding: '2px 8px',
    borderRadius: 99,
    lineHeight: '16px',
  },
  clickableNode: {
    color: '#3b82f6',
    cursor: 'pointer',
    fontWeight: 500,
    fontSize: 12,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  },
  row: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '4px 0',
    fontSize: 12,
  },
  label: {
    color: '#6b7280',
    fontWeight: 500,
    fontSize: 12,
    flexShrink: 0,
  },
  value: {
    color: '#111827',
    fontSize: 12,
    textAlign: 'right' as const,
    wordBreak: 'break-word' as const,
  },
  bar: {
    height: 6,
    borderRadius: 3,
    background: '#e5e7eb',
    flex: 1,
    marginLeft: 8,
    overflow: 'hidden',
  },
  barFill: {
    height: '100%',
    borderRadius: 3,
  },
  listItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    padding: '3px 0',
    fontSize: 12,
    color: '#374151',
  },
  button: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '6px 12px',
    borderRadius: 6,
    border: '1px solid #e5e7eb',
    background: '#fff',
    fontSize: 12,
    fontWeight: 500,
    color: '#374151',
    cursor: 'pointer',
    marginTop: 8,
  },
};
